font_family      Terminess Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12
background #1c1b29
foreground #cfd9d9

selection_background #abd2db
selection_foreground #1c1b29

cursor #abd2db
cursor_text_color #1c1b29

url_color #9ab1ce

window_padding_width 10
adjust_line_height  110%

active_border_color #abd2db
inactive_border_color #353647

# negros
color0  #1c1b29
color8  #515467

# rojos
color1  #6d7284
color9  #929cad

# verdes
color2  #81a3ab
color10 #abd2db

# amarillos
color3  #9aa8b8
color11 #cfd9d9

# azules
color4  #9ab1ce
color12 #abd2db

# magentas
color5  #929cad
color13 #cfd9d9

# cianes
color6  #abd2db
color14 #dbe8e8

# blancos
color7  #cfd9d9
color15 #ffffff
